default_context:
  project_name: 'My Farm App'
  project_slug: 'my-farm-app'
  domain_main: 'my-farm-app.com'
  domain_staging: 'stag.my-farm-app.com'
  domain_base_api_url: 'http://my-farm-app.com/api/v1'
  domain_base_ws_url: 'ws://my-farm-app.com/api/v1'
  docker_swarm_stack_name_main: 'my-farm-app-com'
  docker_swarm_stack_name_staging: 'stag-my-farm-app-com'
  secret_key: 'fVxusUCFpN5Nlicu9vh0viL8DSkApqFW87WxBwLlPT0'
  first_superuser: 'admin@my-farm-app.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.my-farm-app.com", "https://stag.my-farm-app.com", "https://my-farm-app.com"]'
  smtp_tls: 'True'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@my-farm-app.com'
  smtp_emails_from_name: 'Symona Adaro'
  smtp_emails_to_email: 'info@my-farm-app.com'
  mongodb_uri: 'mongodb'
  mongodb_database: 'app'
  traefik_constraint_tag: 'my-farm-app.com'
  traefik_constraint_tag_staging: 'stag.my-farm-app.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/**/*.html, frontend/**/*.vue, frontend/.nuxt/*, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
